name:                haskell-demo
version:             0.1.0.0
github:              "MatrixAI/Haskell-Demo"
license:             Apache
author:              "CMCDragonkai"
maintainer:          "roger.qiu@polyhack.io"
copyright:           "Copyright: (c) 2017 Matrix AI"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/MatrixAI/Haskell-Demo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-demo

tests:
  haskell-demo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-demo
