CREATE EXTENSION IF NOT
EXISTS pgcrypto;

CREATE EXTENSION IF NOT
EXISTS pg_trgm;

CREATE FUNCTION set_updated_on()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_on = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
